### ISSUE TITLE
It doesn't appear possible to control the behaviour of Delegate Factories

### ISSUE THREAD

**Issue by spenceee** [autofac/Autofac.Extras.Moq#1]
There is no way to control or moq behaviour of delegate factories within the Autofac.Extras.Moq package. I've tried numerous ways to mock the delegate factory (so I can provide a specific behaviour) but I either can't control the constructor, or I get a cast exception that the concrete func can't be casted to a Moq.IMocked.

Have I missed something or is this unsupported?

**Comment by tillig** [comment]
[Per note on previously opened issue](https://github.com/autofac/Autofac/issues/636), if you already have a question open on StackOverflow, let's track it and answer it there rather than having cross-posts. All the Autofac devs and contributors are already over there monitoring the `autofac` tag and you'll also have the larger community to help.

If it turns out the functionality you're looking for isn't there, we can open an enhancement request with some details and examples about the kind of thing you're looking for.

Sorry for confusion.
