### ISSUE TITLE
Give the ability to use a different ConstructorFinder

### ISSUE THREAD

**Issue by sebas2day** [autofac/Autofac.Extras.Moq#12]
It would be nice that you could provide types that only has internal constructors and therefor using a different ConstructorFinder than the default one.

**Comment by mareklinka** [comment]
Took a quick look at this and I think this should be feasible. As far as I understand it, a custom constructor finder would only be useful in call to `AutoMock.Create` (for constructing the system under test) and `AutoMock.Provide<TService, TImplementation>` (where TImplementation comes from Autofac resolution).

Any thoughts on this from the maintainers, @tillig?

I would be willing to work on this.

**Comment by tillig** [comment]
Sounds about right. There are several ways to call those methods given that's the majority of the class, but, yeah, that sounds right.

Something that's nagging me in the back of my mind is that this whole thing could get altogether too flexible, trying to expose every feature of Autofac, and that could make usage and maintenance challenging. For example, there's no property injection setup. Do we add a flag for that? We've had to add more to the list of things that can't be automocked so Autofac doesn't complain... Is there more that needs to happen in that area? Where is the line drawn that says, "You've outgrown AutoMock."

On one hand, I feel like this is a reasonable request.

On the other hand, I feel like when folks get into a situation where you outgrow the AutoMock capabilities it may be time to build a real container with mocked registrations set up the way they need to be.

What do you think?

**Comment by mareklinka** [comment]
That is a good point. I did some preliminary work on this to get the feeling for the complexity and it's true the API change didn't sit well with me, it feels like mixing concerns - mocking vs. DI.

However, what you said about setting up custom full container got me thinking. The only reason the more advanced features cannot be used here is because AutoMock creates its own container internally. If we allowed to build an AutoMock instance using an existing container builder, users could setup whatever custom behavior they wanted and still use AutoMock for the simple things.

I'm not sure how complex a change this would be or even if it would make sense in the grand scheme of things, just an idea I got at first glance.

**Comment by tillig** [comment]
Feel free to experiment with that. I won't lie, this particular library has a lot fewer users than many of our others that also have issues to address so it's lower priority.

**Comment by mareklinka** [comment]
Understandable. I think I'll give it a go and see what happens.

**Comment by tillig** [comment]
It's been about a month; I'm going to close this as `wontfix`. If a PR comes in for it, we'll have to consider that and balance it across how much other Autofac specific functionality really needs to be exposed here as well as what it will take to continue maintaining and providing ongoing support.
