### ISSUE TITLE
Using Lazy<T> with AutoMock throws exception

### ISSUE THREAD

**Issue by dampee** [autofac/Autofac.Extras.Moq#3]
I just posted this [earlier on Stackoverflow](http://stackoverflow.com/questions/35855276/how-can-you-use-lazy-with-automock-moq).  But thought this would be a better place.  

---

We are using Autofac.Extras.Moq.AutoMock.
Now I have a constructor dependency using Lazy<>

```
public MyService(Lazy<IDependency> myLazyDependency) {...}
```

to test `MyService` we need to mock the `Lazy<Dependency>`.

I am trying this with

```
private Mock<Lazy<IDependency>> _lazyDependencyMock;

[ClassInitialize]
public static void Init(TestContext context)
{
    autoMock = AutoMock.GetLoose();
}

[TestInitialize]
public void MyTestInitialize()
{
     var myDepMock = autoMock.Mock<Lazy<IDependency>>();  // <-- throws exception
}
```

This is the exception returned by the test runner:

Initialization method Tests.MyServiceTests.MyTestInitialize threw exception. System.InvalidCastException: System.InvalidCastException: Unable to cast object of type 'System.Lazy`1[IDependency]' to type 'Moq.IMocked`1[System.Lazy`1[IDependency]]'..

So, how can I pass a Lazy<> mocked object using automock.

**Comment by tillig** [comment]
Looking at [the source for the auto-mocking registration handler](https://github.com/autofac/Autofac.Extras.Moq/blob/master/src/Autofac.Extras.Moq/MoqRegistrationHandler.cs) it appears we probably need to add exclusion clauses for all of the inherently supported Autofac relationship types - `Lazy<T>`, `Owned<T>`, and so on. Currently there are only exclusions for `IEnumerable<T>` and abstract/interface types.

For now, I'd say try to mock `IDependency` rather than `Lazy<IDependency>` and see what happens. Autofac is what wraps the `Lazy<T>` around the service so you'd be interested in mocking what that thing does rather than what `Lazy<T>` itself is doing internally.

**Comment by dampee** [comment]
That’s it!  Thanks a lot.

Van: Travis Illig [mailto:notifications@github.com]
Verzonden: maandag 7 maart 2016 23:47
Aan: autofac/Autofac.Extras.Moq <Autofac.Extras.Moq@noreply.github.com>
CC: Damiaan Peeters <damiaan@comm-it.be>
Onderwerp: Re: [Autofac.Extras.Moq] using Lazy<> with automock throws exception (#3)


Looking at the source for the auto-mocking registration handler<https://github.com/autofac/Autofac.Extras.Moq/blob/master/src/Autofac.Extras.Moq/MoqRegistrationHandler.cs> it appears we probably need to add exclusion clauses for all of the inherently supported Autofac relationship types - Lazy<T>, Owned<T>, and so on. Currently there are only exclusions for IEnumerable<T> and abstract/interface types.

For now, I'd say try to mock IDependency rather than Lazy<IDependency> and see what happens. Autofac is what wraps the Lazy<T> around the service so you'd be interested in mocking what that thing does rather than what Lazy<T> itself is doing internally.

**Comment by tillig** [comment]
Glad it's working! I'll keep this open so we remember to make that enhancement so the next person doesn't run into the same issue. Thanks!

**Comment by tillig** [comment]
Fix added to release 4.1.0, now published to NuGet.

**Comment by phillipzada** [comment]
Hey guys, 

This has introduced a breaking change when previously it worked and now getting an error

> The lazily-initialized type does not have a public, parameterless constructor.

```
// During test setup, was working with 4.0
mock.Provide(_repositories.Resolve<IListingStateRepository>());
...
whenever the lazy loaded instance is initialised the above error is thrown i.e. instance.Value
```

**Comment by tillig** [comment]
@phillipzada Can you open a new issue with a failing unit test? Due to a screw-up on my part, the fix for `Lazy<T>` and `Owned<T>` got reverted before the 4.1.0 release went out the door, so I don't think it was this change causing your challenges. We did update to Moq 4.7.0, though, so it may be a difference in the way things are interacting. Hence... if you can open a new issue and include a failing unit test so we can repro it and fix it, that'd be great. Failing test + pull request = even better. :)

**Comment by phillipzada** [comment]
Thanks @tillig. Created https://github.com/autofac/Autofac.Extras.Moq/issues/15
