### ISSUE TITLE
GetFromRepository Issue

### ISSUE THREAD

**Issue by Kekstas** [autofac/Autofac.Extras.Moq#41]
I am searching a way to provide Instances after AutoMock is created. I have found GetFromRepository  method where it was seem to be possible to do exactly that. Unfortunately this not working, because newly created AutoMock loosing all mock declarations that was crated with parent Automock. Is There any way to provide instance object to AutoMock?
Here I am  providing a test described issue

```csharp
        [Test]
        public void TestParentMock()
        {
            using var autoMock = AutoMock.GetLoose();

            var moqMockMe = autoMock.Mock<IMockMe>();
            moqMockMe.Setup(s => s.AmIMocked()).Returns("Yes");

            var mockUsage = autoMock.Create<MockUsage>();
            var actualOfParent = mockUsage.IsMockProvided();
            Assert.AreEqual("Yes", actualOfParent); //Pass

            using var scope = AutoMock.GetFromRepository(autoMock.MockRepository, (b) =>
            {
                ///Register new missing instances
            });

            var mockMeInsideScope = scope.Create<MockUsage>();
            var actualOfChild = mockMeInsideScope.IsMockProvided();
            Assert.AreEqual("Yes", actualOfChild,"Child lost parent Mocks");//fails
        }

        
        public interface IMockMe
        {
            string AmIMocked();
        }

        public class MockUsage
        {
            private readonly IMockMe _moc;

            public MockUsage(IMockMe moc)
            {
                _moc = moc;
            }

            public string IsMockProvided()
            {
                return _moc.AmIMocked();
            }
        }
```

**Comment by tillig** [comment]
I'll walk through what I'm seeing, and I'd recommend you also dive in yourself to the source code here because it's not that much.

1. [`AutoMock.GetLoose()`](https://github.com/autofac/Autofac.Extras.Moq/blob/de295b201231269d2e23bf577a5f057f863d70db/src/Autofac.Extras.Moq/AutoMock.cs#L129) ends up [creating a new `MockRepository` with loose behavior](https://github.com/autofac/Autofac.Extras.Moq/blob/de295b201231269d2e23bf577a5f057f863d70db/src/Autofac.Extras.Moq/AutoMock.cs#L53), adds that `MockRepository` to a container, and also [sets up a `MockRegistrationHandler` registration source](https://github.com/autofac/Autofac.Extras.Moq/blob/de295b201231269d2e23bf577a5f057f863d70db/src/Autofac.Extras.Moq/AutoMock.cs#L62).
2. [`AutoMock.Mock<T>()`](https://github.com/autofac/Autofac.Extras.Moq/blob/de295b201231269d2e23bf577a5f057f863d70db/src/Autofac.Extras.Moq/AutoMock.cs#L196) adds the type you want to mock, in this case `IMockMe`, [to the list of mocked types](https://github.com/autofac/Autofac.Extras.Moq/blob/de295b201231269d2e23bf577a5f057f863d70db/src/Autofac.Extras.Moq/AutoMock.cs#L204) and then lets the container "resolve it." This will end up calling...
3. [The `MockRegistrationHandler` registration source](https://github.com/autofac/Autofac.Extras.Moq/blob/de295b201231269d2e23bf577a5f057f863d70db/src/Autofac.Extras.Moq/MoqRegistrationHandler.cs#L116), which will see that you've mocked that object type and will [tell the `MockRepository` to create it for you](https://github.com/autofac/Autofac.Extras.Moq/blob/de295b201231269d2e23bf577a5f057f863d70db/src/Autofac.Extras.Moq/MoqRegistrationHandler.cs#L243).
4. [`AutoMock.Create<T>()`](https://github.com/autofac/Autofac.Extras.Moq/blob/de295b201231269d2e23bf577a5f057f863d70db/src/Autofac.Extras.Moq/AutoMock.cs#L175) will add the type you want to resolve, in this case `MockUsage`, [to the list of created types](https://github.com/autofac/Autofac.Extras.Moq/blob/de295b201231269d2e23bf577a5f057f863d70db/src/Autofac.Extras.Moq/AutoMock.cs#L208) and then the container "resolves it." Again, back to...
5. [`MockRegistrationHandler`, which sees you want the thing created](https://github.com/autofac/Autofac.Extras.Moq/blob/de295b201231269d2e23bf577a5f057f863d70db/src/Autofac.Extras.Moq/MoqRegistrationHandler.cs#L108) and will add the type on the fly to the list of registrations so the container can resolve it.

So far, so good. But here's where it gets tricky and might need someone (you?) to stick a debugger on this and see where things are going awry. A couple of points to consider:

- To optimize performance, once we resolve the set of things from a registration source, we cache that list so we don't re-enumerate things. This is somewhat different from some earlier (pre v6) versions of Autofac that would enumerate these every time.
- As you can see, there's a somewhat confusing mix of "add stuff to the mock repository" and "add stuff to the container to be resolved" going on. Is it all getting transferred right?

**My gut feeling** is that there's something up with the disconnect between what's in the `MockRepository` and what's seen as "created" vs. "mocked" types. In the list above, steps 2 and 4 include adding mocked/created types to separate lists so things get resolved properly. However, when creating one `AutoMock` from a different `AutoMock` those lists aren't transferred. I stopped researching there since I'm kinda out of time, but I think that seems fishy to me.

Unfortunately, I don't think I'll be able to really dive in here for quite a while. Without getting into it... day job pressure has increased greatly.

If you want to figure out what's up, slap a debugger on this thing. [We have SourceLink enabled](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink) so you should be able to step right in and see what's going on if you set your environment up right.

If you do figure it out and figure out how to fix it, we'd love a pull request.

**Comment by Kekstas** [comment]
Thank you for your time investigating this issue. 
I come to same conclusion that the problem is with _createdServiceTypes, _mockedServiceTypes lists that are not transferred to child AutoMock repository. But there is also  IContainer that is not transferred too.
I was starting thinking that method GetFromRepository itself is not enough to create working AutoMock  from another AutoMock. There probably need something similar to Autofac.Container.BeginLifetimeScope that would create new AutoMock and take care of all related complicated things.
I am not sure but it suggest that AutoMock  had no intention to be created from other AutoMock.... 

Thinking about this have give me an idea to register my own serviceSource at AutoMock creation time and similarly like MockRegistrationHandler It gives me ability to add new instance to Container on the fly... without need to create child AutoMock 
Will have to investigate this.

**Comment by tillig** [comment]
It doesn't appear any action is required on this issue and it's been inactive for a couple of years. Closing.
