### ISSUE TITLE
System.InvalidCastException : Unable to cast object of type 'Autofac.Core.Lifetime.LifetimeScope' to 

### ISSUE THREAD

**Issue by dlurton** [autofac/Autofac.Extras.Moq#8]
Hi:

I'm seeing that the following code:

	[TestFixture]
	public class MockingILifetimeScope
	{
		[Test]
		public void FailsWithStackTraceBelow()
		{
			using(var autoMock = AutoMock.GetStrict())
			{
				autoMock.Mock<ILifetimeScope>();
			}
		}

		[Test]
		public void PassesWithoutIssue()
		{
			var mockLifetimeScope = new Mock<ILifetimeScope>();
		}
	}

Results in the following stack trace

    System.InvalidCastException : Unable to cast object of type 'Autofac.Core.Lifetime.LifetimeScope' to type 'Moq.IMocked`1[Autofac.ILifetimeScope]'.
       at Autofac.Extras.Moq.AutoMock.Mock[T](Parameter[] parameters)
       at Sutnova.FeatureApp.Common.Tests.Validation.MockingILifetimeScope.Doh() in     
    <path to .cs file>:line 55

I kinda feel like ILifetimeScope should be mockable with automock, right?

This is with the 4.0.0.0 nuget package.

**Comment by tillig** [comment]
Given the point of AutoMock is to fill in mock things using Autofac, you're going to have trouble mocking Autofac things with Autofac. Sort of like trying to mock a Mock - you'll have trouble there, too.

The specific thing you're hitting with lifetime scope: by default Autofac registers the current lifetime scope inside itself so you can do service location if you want by resolving/injecting a lifetime scope. I'd wager you're running into conflicts trying to mock a thing that really exists.

In general it's best to avoid mocking your IoC container if possible. The point of the IoC container is to inject your dependencies/mocks rather than it, itself, being mocked. Just use the real thing and you should be fine.
